version: 2
updates:
- package-ecosystem: gomod
  directory: "/frontend"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/proxy"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
